### PR TITLE
Rip out vector mapfile setting

### LINKED ISSUE #436: App crash accessing settings since update to Android 10
Yesterday my Fairphone 3 was updated to Android 10. Since then opening the left sidebar and tapping settings causes the app to crash.

Prior to the OS update this wasn't an issue.

Version 3.9.0 on the Google play app store. I have beta updates enabled.

I've tried clearing the cache and app data, both of which have the same crash.

### PR DESCRIPTION
**Pull request by jezhiggins**
Closes #436.

It's causing crashes on some phones, and will be replaced with a new
mechanism soon, see PR #417.

### CODE REVIEW

File: libraries/cyclestreets-fragments/src/main/java/net/cyclestreets/SettingsFragment.kt [hunk 1]
```diff
@@ -165,37 +143,9 @@ class SettingsFragment : PreferenceFragmentCompat(), SharedPreferences.OnSharedP
...
-        var index = mapfilePref.findIndexOfValue(mapfile)
-        if (index == -1)
-            index = 0 // default to something
-
-        mapfilePref.setValueIndex(index)
-        mapfilePref.summary = mapfilePref.entries[index]
-    }
-
-    private fun setAccountSummary() {
+   private fun setAccountSummary() {
```
Comment (oliverlockwood) [inline libraries/cyclestreets-fragments/src/main/java/net/cyclestreets/SettingsFragment.kt:148]: I think you've accidentally de-indented this by 1 character 😂 

I clearly don't care enough to request a change, but you may feel like fixing it as part of your broader PR.

**Comment by oliverlockwood** [comment]
@jezhiggins the only possible issue I can see is: what if someone already has vector maps selected as their preference, and then they upgrade to this version?  What will happen then?

**Comment by jezhiggins** [comment]
It should fallback to the default renderer. In fact it will have already done that as it wouldn't be able to open the map file.

**Review by oliverlockwood — APPROVED** [review]
