### PR TITLE
POI link fixed for Android 11

### LINKED ISSUE #508: POI link not working in Android 11
Recommended course of action is to put a try/catch around the StartActivity when launching the URL:
https://stackoverflow.com/questions/71443029/android-11-resolveactivity

https://developer.android.com/training/package-visibility/use-cases

I'll do this.

### PR DESCRIPTION
**Pull request by HilaryN**
Fixes #508 
Tested on Pixel 4 API 30 (Android 11), Nexus 6 API 29 (Android 10) to check POI link worked, and my own phone, Fairphone 3, Android 11, to check app selector came up.

### CODE REVIEW

**Comment by HilaryN** [comment]
No more space in beta.txt ... ;-)

**Review by jezhiggins — APPROVED** [review]

File: libraries/cyclestreets-view/src/main/java/net/cyclestreets/views/overlay/Bubble.kt [hunk 1]
```diff
@@ -56,9 +56,11 @@ object Bubble {
             val webpage = Uri.parse(url)
             val intent = Intent(Intent.ACTION_VIEW, webpage)
 
-            if (intent.resolveActivity(context.getPackageManager()) != null) {
+            try {
```
Comment (raheemczar) [inline libraries/cyclestreets-view/src/main/java/net/cyclestreets/views/overlay/Bubble.kt:59]: good job
